-- +goose Up

CREATE TABLE IF NOT EXISTS users (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		username TEXT UNIQUE NOT NULL,
		email TEXT NOT NULL DEFAULT '',
		password_hash TEXT NOT NULL,
		salt TEXT NOT NULL,
		require_password_change INTEGER NOT NULL DEFAULT 0,
		failed_attempts INTEGER NOT NULL DEFAULT 0,
		locked_until TIMESTAMP,
		lock_reason TEXT NOT NULL DEFAULT '',
		lock_stage INTEGER NOT NULL DEFAULT 0,
		last_login_at TIMESTAMP,
		last_failed_at TIMESTAMP,
		totp_secret TEXT NOT NULL DEFAULT '',
		totp_enabled INTEGER NOT NULL DEFAULT 0,
		active INTEGER NOT NULL DEFAULT 1,
		created_at TIMESTAMP NOT NULL,
		updated_at TIMESTAMP NOT NULL
	);

CREATE TABLE IF NOT EXISTS roles (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		name TEXT UNIQUE NOT NULL,
		description TEXT NOT NULL DEFAULT '',
		permissions TEXT NOT NULL DEFAULT '[]',
		built_in INTEGER NOT NULL DEFAULT 0,
		template INTEGER NOT NULL DEFAULT 0,
		created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
		updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
	);

CREATE TABLE IF NOT EXISTS user_roles (
		user_id INTEGER NOT NULL,
		role_id INTEGER NOT NULL,
		PRIMARY KEY (user_id, role_id),
		FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
		FOREIGN KEY(role_id) REFERENCES roles(id) ON DELETE CASCADE
	);

CREATE TABLE IF NOT EXISTS sessions (
		id TEXT PRIMARY KEY,
		user_id INTEGER NOT NULL,
		username TEXT NOT NULL,
		roles TEXT NOT NULL,
		csrf_token TEXT NOT NULL,
		ip TEXT NOT NULL DEFAULT '',
		user_agent TEXT NOT NULL DEFAULT '',
		created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
		last_seen_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
		expires_at TIMESTAMP NOT NULL,
		revoked INTEGER NOT NULL DEFAULT 0,
		revoked_at TIMESTAMP,
		revoked_by TEXT NOT NULL DEFAULT ''
	);

CREATE TABLE IF NOT EXISTS audit_log (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		username TEXT NOT NULL,
		action TEXT NOT NULL,
		details TEXT,
		created_at TIMESTAMP NOT NULL
	);

CREATE TABLE IF NOT EXISTS dashboard_layouts (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		user_id INTEGER NOT NULL UNIQUE,
		layout_json TEXT NOT NULL,
		created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
		updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
		FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
	);

CREATE TABLE IF NOT EXISTS doc_folders (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		name TEXT NOT NULL,
		parent_id INTEGER,
		classification_level INTEGER NOT NULL DEFAULT 0,
		classification_tags TEXT NOT NULL DEFAULT '[]',
		inherit_acl INTEGER NOT NULL DEFAULT 1,
		inherit_classification INTEGER NOT NULL DEFAULT 1,
		created_by INTEGER,
		created_at TIMESTAMP NOT NULL,
		updated_at TIMESTAMP NOT NULL,
		FOREIGN KEY(parent_id) REFERENCES doc_folders(id) ON DELETE SET NULL
	);

CREATE TABLE IF NOT EXISTS folder_acl (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		folder_id INTEGER NOT NULL,
		subject_type TEXT NOT NULL,
		subject_id TEXT NOT NULL,
		permission TEXT NOT NULL,
		UNIQUE(folder_id, subject_type, subject_id, permission),
		FOREIGN KEY(folder_id) REFERENCES doc_folders(id) ON DELETE CASCADE
	);

CREATE TABLE IF NOT EXISTS docs (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		folder_id INTEGER,
		title TEXT NOT NULL,
		status TEXT NOT NULL,
		classification_level INTEGER NOT NULL,
		classification_tags TEXT NOT NULL DEFAULT '[]',
		reg_number TEXT NOT NULL UNIQUE,
		doc_type TEXT NOT NULL DEFAULT 'document',
		inherit_acl INTEGER NOT NULL DEFAULT 1,
		inherit_classification INTEGER NOT NULL DEFAULT 1,
		created_by INTEGER,
		current_version INTEGER NOT NULL DEFAULT 0,
		created_at TIMESTAMP NOT NULL,
		updated_at TIMESTAMP NOT NULL,
		deleted_at TIMESTAMP,
		FOREIGN KEY(folder_id) REFERENCES doc_folders(id) ON DELETE SET NULL
	);

CREATE TABLE IF NOT EXISTS doc_versions (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		doc_id INTEGER NOT NULL,
		version INTEGER NOT NULL,
		author_id INTEGER,
		author_username TEXT,
		reason TEXT,
		path TEXT NOT NULL,
		format TEXT NOT NULL,
		size_bytes INTEGER NOT NULL,
		sha256_plain TEXT NOT NULL,
		sha256_cipher TEXT NOT NULL,
		created_at TIMESTAMP NOT NULL,
		UNIQUE(doc_id, version),
		FOREIGN KEY(doc_id) REFERENCES docs(id) ON DELETE CASCADE
	);

CREATE TABLE IF NOT EXISTS doc_acl (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		doc_id INTEGER NOT NULL,
		subject_type TEXT NOT NULL,
		subject_id TEXT NOT NULL,
		permission TEXT NOT NULL,
		UNIQUE(doc_id, subject_type, subject_id, permission),
		FOREIGN KEY(doc_id) REFERENCES docs(id) ON DELETE CASCADE
	);

CREATE TABLE IF NOT EXISTS doc_templates (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		name TEXT NOT NULL,
		description TEXT NOT NULL DEFAULT '',
		format TEXT NOT NULL,
		content TEXT NOT NULL,
		variables TEXT NOT NULL DEFAULT '[]',
		classification_level INTEGER NOT NULL DEFAULT 0,
		classification_tags TEXT NOT NULL DEFAULT '[]',
		created_by INTEGER,
		created_at TIMESTAMP NOT NULL
	);

CREATE TABLE IF NOT EXISTS report_meta (
		doc_id INTEGER PRIMARY KEY,
		period_from TIMESTAMP,
		period_to TIMESTAMP,
		report_status TEXT NOT NULL DEFAULT 'draft',
		template_id INTEGER,
		FOREIGN KEY(doc_id) REFERENCES docs(id) ON DELETE CASCADE
	);

CREATE TABLE IF NOT EXISTS report_templates (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		name TEXT NOT NULL,
		description TEXT NOT NULL DEFAULT '',
		template_markdown TEXT NOT NULL,
		created_by INTEGER,
		created_at TIMESTAMP NOT NULL,
		updated_at TIMESTAMP NOT NULL
	);

CREATE TABLE IF NOT EXISTS report_settings (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		default_classification TEXT NOT NULL DEFAULT 'INTERNAL',
		default_template_id INTEGER,
		header_enabled INTEGER NOT NULL DEFAULT 1,
		header_logo_path TEXT NOT NULL DEFAULT '/gui/static/logo.png',
		header_title TEXT NOT NULL DEFAULT 'Berkut Solutions: Security Control Center',
		watermark_threshold TEXT NOT NULL DEFAULT '',
		updated_at TIMESTAMP NOT NULL
	);

CREATE TABLE IF NOT EXISTS report_sections (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		report_id INTEGER NOT NULL,
		section_type TEXT NOT NULL,
		title TEXT NOT NULL DEFAULT '',
		config_json TEXT NOT NULL DEFAULT '{}',
		order_index INTEGER NOT NULL DEFAULT 0,
		is_enabled INTEGER NOT NULL DEFAULT 1,
		FOREIGN KEY(report_id) REFERENCES docs(id) ON DELETE CASCADE
	);

CREATE TABLE IF NOT EXISTS report_charts (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		report_id INTEGER NOT NULL,
		chart_type TEXT NOT NULL,
		title TEXT NOT NULL DEFAULT '',
		section_type TEXT NOT NULL DEFAULT '',
		config_json TEXT NOT NULL DEFAULT '{}',
		order_index INTEGER NOT NULL DEFAULT 0,
		is_enabled INTEGER NOT NULL DEFAULT 1,
		FOREIGN KEY(report_id) REFERENCES docs(id) ON DELETE CASCADE
	);

CREATE TABLE IF NOT EXISTS report_snapshots (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		report_id INTEGER NOT NULL,
		created_at TIMESTAMP NOT NULL,
		created_by INTEGER,
		reason TEXT NOT NULL DEFAULT '',
		snapshot_json TEXT NOT NULL,
		sha256 TEXT NOT NULL,
		FOREIGN KEY(report_id) REFERENCES docs(id) ON DELETE CASCADE
	);

CREATE TABLE IF NOT EXISTS report_snapshot_items (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		snapshot_id INTEGER NOT NULL,
		entity_type TEXT NOT NULL,
		entity_id TEXT NOT NULL,
		entity_json TEXT NOT NULL,
		created_at TIMESTAMP NOT NULL,
		FOREIGN KEY(snapshot_id) REFERENCES report_snapshots(id) ON DELETE CASCADE
	);

CREATE TABLE IF NOT EXISTS approvals (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		doc_id INTEGER NOT NULL,
		status TEXT NOT NULL,
		message TEXT,
		current_stage INTEGER NOT NULL DEFAULT 1,
		created_by INTEGER NOT NULL,
		created_at TIMESTAMP NOT NULL,
		updated_at TIMESTAMP NOT NULL,
		FOREIGN KEY(doc_id) REFERENCES docs(id) ON DELETE CASCADE
	);

CREATE TABLE IF NOT EXISTS approval_participants (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		approval_id INTEGER NOT NULL,
		user_id INTEGER NOT NULL,
		role TEXT NOT NULL,
		stage INTEGER NOT NULL DEFAULT 1,
		stage_name TEXT NOT NULL DEFAULT '',
		stage_message TEXT NOT NULL DEFAULT '',
		decision TEXT,
		comment TEXT,
		decided_at TIMESTAMP,
		UNIQUE(approval_id, user_id, role, stage),
		FOREIGN KEY(approval_id) REFERENCES approvals(id) ON DELETE CASCADE
	);

CREATE TABLE IF NOT EXISTS doc_export_approvals (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		doc_id INTEGER NOT NULL,
		requested_by INTEGER NOT NULL,
		approved_by INTEGER NOT NULL,
		reason TEXT NOT NULL DEFAULT '',
		created_at TIMESTAMP NOT NULL,
		expires_at TIMESTAMP NOT NULL,
		consumed_at TIMESTAMP,
		FOREIGN KEY(doc_id) REFERENCES docs(id) ON DELETE CASCADE
	);

CREATE TABLE IF NOT EXISTS approval_comments (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		approval_id INTEGER NOT NULL,
		user_id INTEGER NOT NULL,
		comment TEXT NOT NULL,
		created_at TIMESTAMP NOT NULL,
		FOREIGN KEY(approval_id) REFERENCES approvals(id) ON DELETE CASCADE
	);

CREATE TABLE IF NOT EXISTS entity_links (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		doc_id INTEGER NOT NULL,
		source_type TEXT NOT NULL DEFAULT 'doc',
		source_id TEXT NOT NULL DEFAULT '',
		target_type TEXT NOT NULL,
		target_id TEXT NOT NULL,
		relation_type TEXT NOT NULL DEFAULT 'related',
		created_at TIMESTAMP NOT NULL,
		FOREIGN KEY(doc_id) REFERENCES docs(id) ON DELETE CASCADE
	);

CREATE TABLE IF NOT EXISTS doc_reg_counters (
		classification_level INTEGER NOT NULL,
		folder_id INTEGER NOT NULL DEFAULT 0,
		year INTEGER NOT NULL,
		seq INTEGER NOT NULL,
		PRIMARY KEY (classification_level, folder_id, year)
	);

CREATE TABLE IF NOT EXISTS incidents (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		reg_no TEXT NOT NULL UNIQUE,
		title TEXT NOT NULL,
		description TEXT,
		severity TEXT NOT NULL,
		status TEXT NOT NULL DEFAULT 'draft',
		source TEXT NOT NULL DEFAULT '',
		source_ref_id INTEGER,
		closed_at TIMESTAMP,
		closed_by INTEGER,
		owner_user_id INTEGER NOT NULL,
		assignee_user_id INTEGER,
		classification_level INTEGER NOT NULL DEFAULT 1,
		classification_tags TEXT NOT NULL DEFAULT '[]',
		meta_json TEXT NOT NULL DEFAULT '{}',
		created_by INTEGER NOT NULL,
		updated_by INTEGER NOT NULL,
		created_at TIMESTAMP NOT NULL,
		updated_at TIMESTAMP NOT NULL,
		version INTEGER NOT NULL DEFAULT 1,
		deleted_at TIMESTAMP
	);

CREATE TABLE IF NOT EXISTS incident_participants (
		incident_id INTEGER NOT NULL,
		user_id INTEGER NOT NULL,
		role TEXT NOT NULL,
		PRIMARY KEY (incident_id, user_id),
		FOREIGN KEY(incident_id) REFERENCES incidents(id) ON DELETE CASCADE
	);

CREATE TABLE IF NOT EXISTS incident_stages (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		incident_id INTEGER NOT NULL,
		title TEXT NOT NULL,
		position INTEGER NOT NULL,
		created_by INTEGER NOT NULL,
		updated_by INTEGER NOT NULL,
		created_at TIMESTAMP NOT NULL,
		updated_at TIMESTAMP NOT NULL,
		status TEXT NOT NULL DEFAULT 'open',
		closed_at TIMESTAMP,
		closed_by INTEGER,
		is_default INTEGER NOT NULL DEFAULT 0,
		version INTEGER NOT NULL DEFAULT 1,
		FOREIGN KEY(incident_id) REFERENCES incidents(id) ON DELETE CASCADE
	);

CREATE TABLE IF NOT EXISTS incident_stage_entries (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		stage_id INTEGER NOT NULL UNIQUE,
		content TEXT NOT NULL,
		change_reason TEXT NOT NULL DEFAULT '',
		created_by INTEGER NOT NULL,
		updated_by INTEGER NOT NULL,
		created_at TIMESTAMP NOT NULL,
		updated_at TIMESTAMP NOT NULL,
		version INTEGER NOT NULL DEFAULT 1,
		FOREIGN KEY(stage_id) REFERENCES incident_stages(id) ON DELETE CASCADE
	);

CREATE TABLE IF NOT EXISTS incident_acl (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		incident_id INTEGER NOT NULL,
		subject_type TEXT NOT NULL,
		subject_id TEXT NOT NULL,
		permission TEXT NOT NULL,
		UNIQUE(incident_id, subject_type, subject_id, permission),
		FOREIGN KEY(incident_id) REFERENCES incidents(id) ON DELETE CASCADE
	);

CREATE TABLE IF NOT EXISTS incident_reg_counters (
		year INTEGER NOT NULL,
		seq INTEGER NOT NULL,
		PRIMARY KEY (year)
	);

CREATE TABLE IF NOT EXISTS incident_links (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		incident_id INTEGER NOT NULL,
		entity_type TEXT NOT NULL,
		entity_id TEXT NOT NULL,
		title TEXT,
		comment TEXT NOT NULL DEFAULT '',
		unverified INTEGER NOT NULL DEFAULT 0,
		created_by INTEGER NOT NULL,
		created_at TIMESTAMP NOT NULL,
		UNIQUE(incident_id, entity_type, entity_id),
		FOREIGN KEY(incident_id) REFERENCES incidents(id) ON DELETE CASCADE
	);

CREATE TABLE IF NOT EXISTS incident_attachments (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		incident_id INTEGER NOT NULL,
		filename TEXT NOT NULL,
		content_type TEXT NOT NULL,
		size_bytes INTEGER NOT NULL,
		sha256_plain TEXT NOT NULL,
		sha256_cipher TEXT NOT NULL,
		classification_level INTEGER NOT NULL DEFAULT 1,
		classification_tags TEXT NOT NULL DEFAULT '[]',
		uploaded_by INTEGER NOT NULL,
		uploaded_at TIMESTAMP NOT NULL,
		deleted_at TIMESTAMP,
		FOREIGN KEY(incident_id) REFERENCES incidents(id) ON DELETE CASCADE
	);

CREATE TABLE IF NOT EXISTS incident_timeline (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		incident_id INTEGER NOT NULL,
		event_type TEXT NOT NULL,
		message TEXT NOT NULL,
		meta_json TEXT NOT NULL DEFAULT '{}',
		created_by INTEGER NOT NULL,
		created_at TIMESTAMP NOT NULL,
		event_at TIMESTAMP,
		FOREIGN KEY(incident_id) REFERENCES incidents(id) ON DELETE CASCADE
	);

CREATE TABLE IF NOT EXISTS incident_artifact_files (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		incident_id INTEGER NOT NULL,
		artifact_id TEXT NOT NULL,
		filename TEXT NOT NULL,
		content_type TEXT NOT NULL,
		size_bytes INTEGER NOT NULL,
		sha256_plain TEXT NOT NULL,
		sha256_cipher TEXT NOT NULL,
		classification_level INTEGER NOT NULL DEFAULT 1,
		classification_tags TEXT NOT NULL DEFAULT '[]',
		uploaded_by INTEGER NOT NULL,
		uploaded_at TIMESTAMP NOT NULL,
		deleted_at TIMESTAMP,
		FOREIGN KEY(incident_id) REFERENCES incidents(id) ON DELETE CASCADE
	);

CREATE TABLE IF NOT EXISTS docs_fts (content TEXT NOT NULL, doc_id BIGINT NOT NULL, version_id BIGINT NOT NULL, PRIMARY KEY (doc_id, version_id));
CREATE INDEX IF NOT EXISTS idx_docs_fts_doc ON docs_fts(doc_id);

CREATE INDEX IF NOT EXISTS idx_docs_folder ON docs(folder_id);

CREATE INDEX IF NOT EXISTS idx_doc_versions_doc ON doc_versions(doc_id);

CREATE INDEX IF NOT EXISTS idx_approvals_doc ON approvals(doc_id);

CREATE INDEX IF NOT EXISTS idx_doc_export_approvals_doc ON doc_export_approvals(doc_id, requested_by, expires_at);

CREATE INDEX IF NOT EXISTS idx_entity_links_doc ON entity_links(doc_id);

CREATE INDEX IF NOT EXISTS idx_incidents_status ON incidents(status);

CREATE INDEX IF NOT EXISTS idx_incidents_severity ON incidents(severity);

CREATE INDEX IF NOT EXISTS idx_incidents_owner ON incidents(owner_user_id);

CREATE INDEX IF NOT EXISTS idx_incidents_assignee ON incidents(assignee_user_id);

CREATE INDEX IF NOT EXISTS idx_incidents_created ON incidents(created_at);

CREATE INDEX IF NOT EXISTS idx_incident_participants_user ON incident_participants(user_id);

CREATE INDEX IF NOT EXISTS idx_incident_stages_incident ON incident_stages(incident_id);

CREATE INDEX IF NOT EXISTS idx_incident_stage_entries_stage ON incident_stage_entries(stage_id);

CREATE INDEX IF NOT EXISTS idx_incident_acl_incident ON incident_acl(incident_id);

CREATE INDEX IF NOT EXISTS idx_incident_links_incident ON incident_links(incident_id);

CREATE INDEX IF NOT EXISTS idx_incident_attachments_incident ON incident_attachments(incident_id);

CREATE INDEX IF NOT EXISTS idx_incident_artifact_files_incident ON incident_artifact_files(incident_id);

CREATE INDEX IF NOT EXISTS idx_incident_artifact_files_artifact ON incident_artifact_files(artifact_id);

CREATE INDEX IF NOT EXISTS idx_incident_timeline_incident ON incident_timeline(incident_id);

CREATE INDEX IF NOT EXISTS idx_report_charts_report ON report_charts(report_id);

CREATE TABLE IF NOT EXISTS groups (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		name TEXT UNIQUE NOT NULL,
		description TEXT NOT NULL DEFAULT '',
		clearance_level INTEGER NOT NULL DEFAULT 0,
		clearance_tags TEXT NOT NULL DEFAULT '[]',
		menu_permissions TEXT NOT NULL DEFAULT '[]',
		is_system INTEGER NOT NULL DEFAULT 0,
		created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
		updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
	);

CREATE TABLE IF NOT EXISTS group_roles (
		group_id INTEGER NOT NULL,
		role_id INTEGER NOT NULL,
		PRIMARY KEY(group_id, role_id),
		FOREIGN KEY(group_id) REFERENCES groups(id) ON DELETE CASCADE,
		FOREIGN KEY(role_id) REFERENCES roles(id) ON DELETE CASCADE
	);

CREATE TABLE IF NOT EXISTS user_groups (
		user_id INTEGER NOT NULL,
		group_id INTEGER NOT NULL,
		PRIMARY KEY(user_id, group_id),
		FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
		FOREIGN KEY(group_id) REFERENCES groups(id) ON DELETE CASCADE
	);

CREATE TABLE IF NOT EXISTS password_history (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		user_id INTEGER NOT NULL,
		password_hash TEXT NOT NULL,
		salt TEXT NOT NULL,
		created_at TIMESTAMP NOT NULL,
		FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
	);

CREATE TABLE IF NOT EXISTS login_events (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		user_id INTEGER,
		username TEXT NOT NULL,
		event TEXT NOT NULL,
		details TEXT NOT NULL DEFAULT '',
		created_at TIMESTAMP NOT NULL,
		FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL
	);

CREATE TABLE IF NOT EXISTS controls (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		code TEXT NOT NULL UNIQUE,
		title TEXT NOT NULL,
		description_md TEXT NOT NULL DEFAULT '',
		control_type TEXT NOT NULL,
		domain TEXT NOT NULL,
		owner_user_id INTEGER,
		review_frequency TEXT NOT NULL,
		status TEXT NOT NULL,
		risk_level TEXT NOT NULL,
		tags_json TEXT NOT NULL DEFAULT '[]',
		created_by INTEGER NOT NULL,
		created_at TIMESTAMP NOT NULL,
		updated_at TIMESTAMP NOT NULL,
		is_active INTEGER NOT NULL DEFAULT 1
	);

CREATE TABLE IF NOT EXISTS control_types (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		name TEXT NOT NULL UNIQUE,
		is_builtin INTEGER NOT NULL DEFAULT 0,
		created_at TIMESTAMP NOT NULL
	);

CREATE INDEX IF NOT EXISTS idx_control_types_name ON control_types(name);

CREATE TABLE IF NOT EXISTS control_checks (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		control_id INTEGER NOT NULL,
		checked_at TIMESTAMP NOT NULL,
		checked_by INTEGER,
		result TEXT NOT NULL,
		notes_md TEXT NOT NULL DEFAULT '',
		evidence_links_json TEXT NOT NULL DEFAULT '[]',
		created_at TIMESTAMP NOT NULL,
		FOREIGN KEY(control_id) REFERENCES controls(id) ON DELETE CASCADE
	);

CREATE TABLE IF NOT EXISTS control_comments (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		control_id INTEGER NOT NULL,
		author_id INTEGER NOT NULL,
		content TEXT NOT NULL,
		attachments TEXT NOT NULL DEFAULT '[]',
		created_at TIMESTAMP NOT NULL,
		FOREIGN KEY(control_id) REFERENCES controls(id) ON DELETE CASCADE,
		FOREIGN KEY(author_id) REFERENCES users(id) ON DELETE CASCADE
	);

CREATE INDEX IF NOT EXISTS idx_control_comments_control ON control_comments(control_id);

CREATE TABLE IF NOT EXISTS control_violations (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		control_id INTEGER NOT NULL,
		incident_id INTEGER,
		happened_at TIMESTAMP NOT NULL,
		severity TEXT NOT NULL,
		summary TEXT NOT NULL,
		impact_md TEXT NOT NULL DEFAULT '',
		created_by INTEGER NOT NULL,
		created_at TIMESTAMP NOT NULL,
		is_auto INTEGER NOT NULL DEFAULT 0,
		is_active INTEGER NOT NULL DEFAULT 1,
		FOREIGN KEY(control_id) REFERENCES controls(id) ON DELETE CASCADE
	);

CREATE TABLE IF NOT EXISTS control_frameworks (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		name TEXT NOT NULL,
		version TEXT NOT NULL DEFAULT '',
		is_active INTEGER NOT NULL DEFAULT 1
	);

CREATE TABLE IF NOT EXISTS control_framework_items (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		framework_id INTEGER NOT NULL,
		code TEXT NOT NULL,
		title TEXT NOT NULL,
		description_md TEXT NOT NULL DEFAULT '',
		UNIQUE(framework_id, code),
		FOREIGN KEY(framework_id) REFERENCES control_frameworks(id) ON DELETE CASCADE
	);

CREATE TABLE IF NOT EXISTS control_framework_map (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		framework_item_id INTEGER NOT NULL,
		control_id INTEGER NOT NULL,
		UNIQUE(framework_item_id, control_id),
		FOREIGN KEY(framework_item_id) REFERENCES control_framework_items(id) ON DELETE CASCADE,
		FOREIGN KEY(control_id) REFERENCES controls(id) ON DELETE CASCADE
	);

CREATE INDEX IF NOT EXISTS idx_controls_code ON controls(code);

CREATE INDEX IF NOT EXISTS idx_controls_status ON controls(status);

CREATE INDEX IF NOT EXISTS idx_controls_risk ON controls(risk_level);

CREATE INDEX IF NOT EXISTS idx_controls_domain ON controls(domain);

CREATE INDEX IF NOT EXISTS idx_controls_owner ON controls(owner_user_id);

CREATE INDEX IF NOT EXISTS idx_control_checks_control ON control_checks(control_id);

CREATE INDEX IF NOT EXISTS idx_control_checks_checked ON control_checks(checked_at);

CREATE INDEX IF NOT EXISTS idx_control_violations_control ON control_violations(control_id);

CREATE INDEX IF NOT EXISTS idx_control_violations_incident ON control_violations(incident_id);

CREATE INDEX IF NOT EXISTS idx_control_framework_items_framework ON control_framework_items(framework_id);

CREATE INDEX IF NOT EXISTS idx_control_framework_map_item ON control_framework_map(framework_item_id);

CREATE INDEX IF NOT EXISTS idx_control_framework_map_control ON control_framework_map(control_id);

CREATE TABLE IF NOT EXISTS monitors (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		name TEXT NOT NULL,
		type TEXT NOT NULL,
		url TEXT,
		host TEXT,
		port INTEGER,
		method TEXT NOT NULL DEFAULT 'GET',
		request_body TEXT,
		request_body_type TEXT NOT NULL DEFAULT 'none',
		headers_json TEXT NOT NULL DEFAULT '{}',
		interval_sec INTEGER NOT NULL DEFAULT 60,
		timeout_sec INTEGER NOT NULL DEFAULT 5,
		retries INTEGER NOT NULL DEFAULT 0,
		retry_interval_sec INTEGER NOT NULL DEFAULT 5,
		allowed_status_json TEXT NOT NULL DEFAULT '["200-299"]',
		ignore_tls_errors INTEGER NOT NULL DEFAULT 0,
		notify_tls_expiring INTEGER NOT NULL DEFAULT 1,
		is_active INTEGER NOT NULL DEFAULT 1,
		is_paused INTEGER NOT NULL DEFAULT 0,
		tags_json TEXT NOT NULL DEFAULT '[]',
		group_id INTEGER,
		sla_target_pct REAL,
		auto_incident INTEGER NOT NULL DEFAULT 0,
		auto_task_on_down INTEGER NOT NULL DEFAULT 0,
		incident_severity TEXT NOT NULL DEFAULT 'low',
		incident_type_id TEXT NOT NULL DEFAULT '',
		created_by INTEGER,
		created_at TIMESTAMP NOT NULL,
		updated_at TIMESTAMP NOT NULL
	);

CREATE TABLE IF NOT EXISTS monitor_state (
		monitor_id INTEGER PRIMARY KEY,
		status TEXT NOT NULL,
		last_result_status TEXT NOT NULL DEFAULT '',
		maintenance_active INTEGER NOT NULL DEFAULT 0,
		last_checked_at TIMESTAMP,
		last_up_at TIMESTAMP,
		last_down_at TIMESTAMP,
		last_latency_ms INTEGER,
		last_status_code INTEGER,
		last_error TEXT,
		uptime_24h REAL NOT NULL DEFAULT 0,
		uptime_30d REAL NOT NULL DEFAULT 0,
		avg_latency_24h REAL NOT NULL DEFAULT 0,
		tls_days_left INTEGER,
		tls_not_after TIMESTAMP,
		FOREIGN KEY(monitor_id) REFERENCES monitors(id) ON DELETE CASCADE
	);

CREATE TABLE IF NOT EXISTS monitor_metrics (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		monitor_id INTEGER NOT NULL,
		ts TIMESTAMP NOT NULL,
		latency_ms INTEGER NOT NULL DEFAULT 0,
		ok INTEGER NOT NULL DEFAULT 0,
		status_code INTEGER,
		error TEXT,
		FOREIGN KEY(monitor_id) REFERENCES monitors(id) ON DELETE CASCADE
	);

CREATE TABLE IF NOT EXISTS monitor_events (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		monitor_id INTEGER NOT NULL,
		ts TIMESTAMP NOT NULL,
		event_type TEXT NOT NULL,
		message TEXT NOT NULL,
		FOREIGN KEY(monitor_id) REFERENCES monitors(id) ON DELETE CASCADE
	);

CREATE TABLE IF NOT EXISTS monitor_tls (
		monitor_id INTEGER PRIMARY KEY,
		checked_at TIMESTAMP NOT NULL,
		not_after TIMESTAMP NOT NULL,
		not_before TIMESTAMP NOT NULL,
		common_name TEXT NOT NULL DEFAULT '',
		issuer TEXT NOT NULL DEFAULT '',
		san_json TEXT NOT NULL DEFAULT '[]',
		fingerprint_sha256 TEXT NOT NULL DEFAULT '',
		last_error TEXT,
		FOREIGN KEY(monitor_id) REFERENCES monitors(id) ON DELETE CASCADE
	);

CREATE TABLE IF NOT EXISTS monitor_maintenance (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		name TEXT NOT NULL,
		description_md TEXT NOT NULL DEFAULT '',
		monitor_id INTEGER,
		monitor_ids_json TEXT NOT NULL DEFAULT '[]',
		tags_json TEXT,
		starts_at TIMESTAMP NOT NULL,
		ends_at TIMESTAMP NOT NULL,
		timezone TEXT NOT NULL DEFAULT '',
		strategy TEXT NOT NULL DEFAULT 'single',
		strategy_json TEXT NOT NULL DEFAULT '{}',
		is_recurring INTEGER NOT NULL DEFAULT 0,
		rrule_text TEXT,
		created_by INTEGER,
		created_at TIMESTAMP NOT NULL,
		updated_at TIMESTAMP NOT NULL,
		is_active INTEGER NOT NULL DEFAULT 1,
		stopped_at TIMESTAMP,
		stopped_by INTEGER,
		FOREIGN KEY(monitor_id) REFERENCES monitors(id) ON DELETE CASCADE
	);

CREATE TABLE IF NOT EXISTS monitoring_settings (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		retention_days INTEGER NOT NULL DEFAULT 30,
		max_concurrent_checks INTEGER NOT NULL DEFAULT 10,
		default_timeout_sec INTEGER NOT NULL DEFAULT 5,
		default_interval_sec INTEGER NOT NULL DEFAULT 60,
		engine_enabled INTEGER NOT NULL DEFAULT 1,
		allow_private_networks INTEGER NOT NULL DEFAULT 0,
		tls_refresh_hours INTEGER NOT NULL DEFAULT 24,
		tls_expiring_days INTEGER NOT NULL DEFAULT 30,
		notify_suppress_minutes INTEGER NOT NULL DEFAULT 5,
		notify_repeat_down_minutes INTEGER NOT NULL DEFAULT 30,
		notify_maintenance INTEGER NOT NULL DEFAULT 0,
		auto_task_on_down INTEGER NOT NULL DEFAULT 1,
		auto_tls_incident INTEGER NOT NULL DEFAULT 1,
		auto_tls_incident_days INTEGER NOT NULL DEFAULT 14,
		default_retries INTEGER NOT NULL DEFAULT 2,
		default_retry_interval_sec INTEGER NOT NULL DEFAULT 30,
		default_sla_target_pct REAL NOT NULL DEFAULT 90,
		updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
	);

CREATE TABLE IF NOT EXISTS notification_channels (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		type TEXT NOT NULL,
		name TEXT NOT NULL,
		telegram_bot_token BYTEA NOT NULL,
		telegram_chat_id TEXT NOT NULL,
		telegram_thread_id INTEGER,
		silent INTEGER NOT NULL DEFAULT 0,
		protect_content INTEGER NOT NULL DEFAULT 0,
		is_default INTEGER NOT NULL DEFAULT 0,
		created_by INTEGER,
		created_at TIMESTAMP NOT NULL,
		is_active INTEGER NOT NULL DEFAULT 1
	);

CREATE TABLE IF NOT EXISTS monitor_notifications (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		monitor_id INTEGER NOT NULL,
		notification_channel_id INTEGER NOT NULL,
		enabled INTEGER NOT NULL DEFAULT 1,
		FOREIGN KEY(monitor_id) REFERENCES monitors(id) ON DELETE CASCADE,
		FOREIGN KEY(notification_channel_id) REFERENCES notification_channels(id) ON DELETE CASCADE
	);

CREATE TABLE IF NOT EXISTS monitor_notification_state (
		monitor_id INTEGER PRIMARY KEY,
		last_notified_at TIMESTAMP,
		last_down_notified_at TIMESTAMP,
		last_up_notified_at TIMESTAMP,
		last_tls_notified_at TIMESTAMP,
		last_maintenance_notified_at TIMESTAMP,
		down_started_at TIMESTAMP,
		down_sequence INTEGER NOT NULL DEFAULT 0,
		FOREIGN KEY(monitor_id) REFERENCES monitors(id) ON DELETE CASCADE
	);

CREATE TABLE IF NOT EXISTS monitor_notification_deliveries (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		monitor_id INTEGER,
		notification_channel_id INTEGER NOT NULL,
		event_type TEXT NOT NULL DEFAULT '',
		status TEXT NOT NULL DEFAULT '',
		error_text TEXT NOT NULL DEFAULT '',
		body_preview TEXT NOT NULL DEFAULT '',
		created_at TIMESTAMP NOT NULL,
		acknowledged_at TIMESTAMP,
		acknowledged_by INTEGER,
		FOREIGN KEY(monitor_id) REFERENCES monitors(id) ON DELETE SET NULL,
		FOREIGN KEY(notification_channel_id) REFERENCES notification_channels(id) ON DELETE CASCADE
	);

CREATE TABLE IF NOT EXISTS app_https_settings (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		mode TEXT NOT NULL DEFAULT 'disabled',
		listen_port INTEGER NOT NULL DEFAULT 8080,
		trusted_proxies_json TEXT NOT NULL DEFAULT '[]',
		builtin_cert_path TEXT NOT NULL DEFAULT '',
		builtin_key_path TEXT NOT NULL DEFAULT '',
		external_proxy_hint TEXT NOT NULL DEFAULT '',
		updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
	);

CREATE TABLE IF NOT EXISTS app_runtime_settings (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		deployment_mode TEXT NOT NULL DEFAULT 'enterprise',
		update_checks_enabled INTEGER NOT NULL DEFAULT 0,
		updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
	);

CREATE INDEX IF NOT EXISTS idx_monitors_name ON monitors(name);

CREATE INDEX IF NOT EXISTS idx_monitor_metrics_monitor_ts ON monitor_metrics(monitor_id, ts);

CREATE INDEX IF NOT EXISTS idx_monitor_events_monitor_ts ON monitor_events(monitor_id, ts);

CREATE INDEX IF NOT EXISTS idx_monitor_tls_checked ON monitor_tls(checked_at);

CREATE INDEX IF NOT EXISTS idx_monitor_maintenance_window ON monitor_maintenance(starts_at, ends_at);

CREATE INDEX IF NOT EXISTS idx_notification_channels_default ON notification_channels(is_default, is_active);

CREATE INDEX IF NOT EXISTS idx_monitor_notifications_monitor ON monitor_notifications(monitor_id);

CREATE INDEX IF NOT EXISTS idx_monitor_notification_deliveries_created ON monitor_notification_deliveries(created_at);

CREATE INDEX IF NOT EXISTS idx_monitor_notification_deliveries_status ON monitor_notification_deliveries(status, acknowledged_at);

CREATE TABLE IF NOT EXISTS task_boards (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		organization_id TEXT NOT NULL DEFAULT '',
		name TEXT NOT NULL,
		description TEXT NOT NULL DEFAULT '',
		default_template_id INTEGER,
		created_by INTEGER,
		created_at TIMESTAMP NOT NULL,
		updated_at TIMESTAMP NOT NULL,
		is_active INTEGER NOT NULL DEFAULT 1,
		FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL
	);

CREATE TABLE IF NOT EXISTS task_board_acl (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		board_id INTEGER NOT NULL,
		subject_type TEXT NOT NULL,
		subject_id TEXT NOT NULL,
		permission TEXT NOT NULL,
		UNIQUE(board_id, subject_type, subject_id, permission),
		FOREIGN KEY(board_id) REFERENCES task_boards(id) ON DELETE CASCADE
	);

CREATE TABLE IF NOT EXISTS task_columns (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		board_id INTEGER NOT NULL,
		name TEXT NOT NULL,
		position INTEGER NOT NULL,
		is_final INTEGER NOT NULL DEFAULT 0,
		wip_limit INTEGER,
		default_template_id INTEGER,
		is_active INTEGER NOT NULL DEFAULT 1,
		created_at TIMESTAMP NOT NULL,
		updated_at TIMESTAMP NOT NULL,
		FOREIGN KEY(board_id) REFERENCES task_boards(id) ON DELETE CASCADE
	);

CREATE TABLE IF NOT EXISTS task_subcolumns (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		column_id INTEGER NOT NULL,
		name TEXT NOT NULL,
		position INTEGER NOT NULL,
		is_active INTEGER NOT NULL DEFAULT 1,
		created_at TIMESTAMP NOT NULL,
		updated_at TIMESTAMP NOT NULL,
		FOREIGN KEY(column_id) REFERENCES task_columns(id) ON DELETE CASCADE
	);

CREATE TABLE IF NOT EXISTS tasks (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		board_id INTEGER NOT NULL,
		column_id INTEGER NOT NULL,
		subcolumn_id INTEGER,
		title TEXT NOT NULL,
		description TEXT NOT NULL DEFAULT '',
		result TEXT NOT NULL DEFAULT '',
		external_link TEXT NOT NULL DEFAULT '',
		business_customer TEXT NOT NULL DEFAULT '',
		status TEXT NOT NULL DEFAULT '',
		priority TEXT NOT NULL,
		template_id INTEGER,
		recurring_rule_id INTEGER,
		checklist TEXT NOT NULL DEFAULT '[]',
		size_estimate INTEGER,
		created_by INTEGER,
		due_date TIMESTAMP,
		created_at TIMESTAMP NOT NULL,
		updated_at TIMESTAMP NOT NULL,
		closed_at TIMESTAMP,
		is_archived INTEGER NOT NULL DEFAULT 0,
		position INTEGER NOT NULL DEFAULT 0,
		FOREIGN KEY(board_id) REFERENCES task_boards(id) ON DELETE CASCADE,
		FOREIGN KEY(column_id) REFERENCES task_columns(id) ON DELETE RESTRICT,
		FOREIGN KEY(subcolumn_id) REFERENCES task_subcolumns(id) ON DELETE SET NULL,
		FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL
	);

CREATE TABLE IF NOT EXISTS task_archive_entries (
		task_id INTEGER PRIMARY KEY,
		archived_at TIMESTAMP NOT NULL,
		archived_by INTEGER,
		archived_board_id INTEGER NOT NULL,
		archived_column_id INTEGER NOT NULL,
		archived_subcolumn_id INTEGER,
		original_position INTEGER NOT NULL DEFAULT 0,
		restored_at TIMESTAMP,
		restored_by INTEGER,
		FOREIGN KEY(task_id) REFERENCES tasks(id) ON DELETE CASCADE,
		FOREIGN KEY(archived_by) REFERENCES users(id) ON DELETE SET NULL,
		FOREIGN KEY(restored_by) REFERENCES users(id) ON DELETE SET NULL
	);

CREATE TABLE IF NOT EXISTS task_assignments (
		task_id INTEGER NOT NULL,
		user_id INTEGER NOT NULL,
		assigned_at TIMESTAMP NOT NULL,
		assigned_by INTEGER,
		PRIMARY KEY(task_id, user_id),
		FOREIGN KEY(task_id) REFERENCES tasks(id) ON DELETE CASCADE,
		FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
		FOREIGN KEY(assigned_by) REFERENCES users(id) ON DELETE SET NULL
	);

CREATE TABLE IF NOT EXISTS task_comments (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		task_id INTEGER NOT NULL,
		author_id INTEGER NOT NULL,
		content TEXT NOT NULL,
		created_at TIMESTAMP NOT NULL,
		FOREIGN KEY(task_id) REFERENCES tasks(id) ON DELETE CASCADE,
		FOREIGN KEY(author_id) REFERENCES users(id) ON DELETE CASCADE
	);

CREATE TABLE IF NOT EXISTS task_blocks (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		task_id INTEGER NOT NULL,
		block_type TEXT NOT NULL,
		reason TEXT,
		blocker_task_id INTEGER,
		created_by INTEGER,
		created_at TIMESTAMP NOT NULL,
		resolved_by INTEGER,
		resolved_at TIMESTAMP,
		is_active INTEGER NOT NULL DEFAULT 1,
		FOREIGN KEY(task_id) REFERENCES tasks(id) ON DELETE CASCADE,
		FOREIGN KEY(blocker_task_id) REFERENCES tasks(id) ON DELETE SET NULL,
		FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL,
		FOREIGN KEY(resolved_by) REFERENCES users(id) ON DELETE SET NULL
	);

CREATE INDEX IF NOT EXISTS idx_task_boards_active ON task_boards(is_active);

CREATE INDEX IF NOT EXISTS idx_task_columns_board ON task_columns(board_id);

CREATE INDEX IF NOT EXISTS idx_task_columns_active ON task_columns(is_active);

CREATE INDEX IF NOT EXISTS idx_task_subcolumns_column ON task_subcolumns(column_id);

CREATE INDEX IF NOT EXISTS idx_task_subcolumns_active ON task_subcolumns(is_active);

CREATE INDEX IF NOT EXISTS idx_tasks_board ON tasks(board_id);

CREATE INDEX IF NOT EXISTS idx_tasks_column ON tasks(column_id);

CREATE INDEX IF NOT EXISTS idx_tasks_subcolumn ON tasks(subcolumn_id);

CREATE INDEX IF NOT EXISTS idx_tasks_status ON tasks(status);

CREATE INDEX IF NOT EXISTS idx_tasks_due_date ON tasks(due_date);

CREATE INDEX IF NOT EXISTS idx_tasks_archived ON tasks(is_archived);

CREATE INDEX IF NOT EXISTS idx_task_archive_entries_archived_at ON task_archive_entries(archived_at);

CREATE INDEX IF NOT EXISTS idx_task_archive_entries_board ON task_archive_entries(archived_board_id);

CREATE INDEX IF NOT EXISTS idx_task_assignments_user ON task_assignments(user_id);

CREATE INDEX IF NOT EXISTS idx_task_assignments_task ON task_assignments(task_id);

CREATE INDEX IF NOT EXISTS idx_task_comments_task ON task_comments(task_id);

CREATE INDEX IF NOT EXISTS idx_task_blocks_task ON task_blocks(task_id);

CREATE INDEX IF NOT EXISTS idx_task_blocks_blocker ON task_blocks(blocker_task_id);

CREATE INDEX IF NOT EXISTS idx_task_blocks_active ON task_blocks(is_active);

CREATE TABLE IF NOT EXISTS task_files (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		task_id INTEGER NOT NULL,
		name TEXT NOT NULL,
		stored_name TEXT NOT NULL,
		content_type TEXT NOT NULL,
		size_bytes INTEGER NOT NULL,
		uploaded_by INTEGER,
		uploaded_at TIMESTAMP NOT NULL,
		FOREIGN KEY(task_id) REFERENCES tasks(id) ON DELETE CASCADE,
		FOREIGN KEY(uploaded_by) REFERENCES users(id) ON DELETE SET NULL
	);

CREATE INDEX IF NOT EXISTS idx_task_files_task ON task_files(task_id);

CREATE INDEX IF NOT EXISTS idx_task_board_acl_board ON task_board_acl(board_id);

CREATE TABLE IF NOT EXISTS task_templates (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		board_id INTEGER NOT NULL,
		column_id INTEGER NOT NULL,
		title_template TEXT NOT NULL,
		description_template TEXT NOT NULL DEFAULT '',
		priority TEXT NOT NULL,
		default_assignees TEXT NOT NULL DEFAULT '[]',
		default_due_days INTEGER NOT NULL DEFAULT 0,
		checklist_template TEXT NOT NULL DEFAULT '[]',
		links_template TEXT NOT NULL DEFAULT '[]',
		is_active INTEGER NOT NULL DEFAULT 1,
		created_by INTEGER,
		created_at TIMESTAMP NOT NULL,
		updated_at TIMESTAMP NOT NULL,
		FOREIGN KEY(board_id) REFERENCES task_boards(id) ON DELETE CASCADE,
		FOREIGN KEY(column_id) REFERENCES task_columns(id) ON DELETE RESTRICT,
		FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL
	);

CREATE TABLE IF NOT EXISTS task_recurring_rules (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		template_id INTEGER NOT NULL,
		schedule_type TEXT NOT NULL,
		schedule_config TEXT NOT NULL DEFAULT '{}',
		time_of_day TEXT NOT NULL,
		next_run_at TIMESTAMP,
		last_run_at TIMESTAMP,
		is_active INTEGER NOT NULL DEFAULT 1,
		created_by INTEGER,
		created_at TIMESTAMP NOT NULL,
		updated_at TIMESTAMP NOT NULL,
		FOREIGN KEY(template_id) REFERENCES task_templates(id) ON DELETE CASCADE,
		FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL
	);

CREATE TABLE IF NOT EXISTS task_recurring_instances (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		rule_id INTEGER NOT NULL,
		template_id INTEGER NOT NULL,
		task_id INTEGER,
		scheduled_for TIMESTAMP NOT NULL,
		created_at TIMESTAMP NOT NULL,
		UNIQUE(rule_id, scheduled_for),
		FOREIGN KEY(rule_id) REFERENCES task_recurring_rules(id) ON DELETE CASCADE,
		FOREIGN KEY(template_id) REFERENCES task_templates(id) ON DELETE CASCADE,
		FOREIGN KEY(task_id) REFERENCES tasks(id) ON DELETE SET NULL
	);

CREATE INDEX IF NOT EXISTS idx_task_templates_board ON task_templates(board_id);

CREATE INDEX IF NOT EXISTS idx_task_templates_active ON task_templates(is_active);

CREATE INDEX IF NOT EXISTS idx_task_recurring_rules_template ON task_recurring_rules(template_id);

CREATE INDEX IF NOT EXISTS idx_task_recurring_rules_active ON task_recurring_rules(is_active);

CREATE INDEX IF NOT EXISTS idx_task_recurring_rules_next_run ON task_recurring_rules(next_run_at);

CREATE INDEX IF NOT EXISTS idx_task_recurring_instances_rule ON task_recurring_instances(rule_id);

CREATE INDEX IF NOT EXISTS idx_task_recurring_instances_task ON task_recurring_instances(task_id);

CREATE TABLE IF NOT EXISTS task_spaces (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		organization_id TEXT NOT NULL DEFAULT '',
		name TEXT NOT NULL,
		description TEXT NOT NULL DEFAULT '',
		layout TEXT NOT NULL DEFAULT 'row',
		created_by INTEGER,
		created_at TIMESTAMP NOT NULL,
		updated_at TIMESTAMP NOT NULL,
		is_active INTEGER NOT NULL DEFAULT 1,
		FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL
	);

CREATE TABLE IF NOT EXISTS task_space_acl (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		space_id INTEGER NOT NULL,
		subject_type TEXT NOT NULL,
		subject_id TEXT NOT NULL,
		permission TEXT NOT NULL,
		UNIQUE(space_id, subject_type, subject_id, permission),
		FOREIGN KEY(space_id) REFERENCES task_spaces(id) ON DELETE CASCADE
	);

CREATE INDEX IF NOT EXISTS idx_task_spaces_active ON task_spaces(is_active);

CREATE INDEX IF NOT EXISTS idx_task_space_acl_space ON task_space_acl(space_id);

CREATE TABLE IF NOT EXISTS task_tags (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		name TEXT NOT NULL UNIQUE,
		created_at TIMESTAMP NOT NULL
	);

CREATE TABLE IF NOT EXISTS task_tag_links (
		task_id INTEGER NOT NULL,
		tag_id INTEGER NOT NULL,
		created_at TIMESTAMP NOT NULL,
		PRIMARY KEY(task_id, tag_id),
		FOREIGN KEY(task_id) REFERENCES tasks(id) ON DELETE CASCADE,
		FOREIGN KEY(tag_id) REFERENCES task_tags(id) ON DELETE CASCADE
	);

CREATE INDEX IF NOT EXISTS idx_task_tag_links_task ON task_tag_links(task_id);

CREATE INDEX IF NOT EXISTS idx_task_tag_links_tag ON task_tag_links(tag_id);

CREATE TABLE IF NOT EXISTS task_board_layouts (
		user_id INTEGER NOT NULL,
		space_id INTEGER NOT NULL,
		layout_json TEXT NOT NULL,
		created_at TIMESTAMP NOT NULL,
		updated_at TIMESTAMP NOT NULL,
		PRIMARY KEY(user_id, space_id),
		FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
		FOREIGN KEY(space_id) REFERENCES task_spaces(id) ON DELETE CASCADE
	);

CREATE INDEX IF NOT EXISTS idx_task_board_layouts_space ON task_board_layouts(space_id);

ALTER TABLE users ADD COLUMN IF NOT EXISTS full_name TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS department TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS position TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS clearance_level INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS clearance_tags TEXT NOT NULL DEFAULT '[]';
ALTER TABLE users ADD COLUMN IF NOT EXISTS password_set INTEGER DEFAULT 1;
ALTER TABLE users ADD COLUMN IF NOT EXISTS disabled_at TIMESTAMP;
ALTER TABLE users ADD COLUMN IF NOT EXISTS password_changed_at TIMESTAMP;
ALTER TABLE task_comments ADD COLUMN IF NOT EXISTS attachments TEXT NOT NULL DEFAULT '[]';
ALTER TABLE task_boards ADD COLUMN IF NOT EXISTS space_id INTEGER DEFAULT 0;
ALTER TABLE task_boards ADD COLUMN IF NOT EXISTS position INTEGER DEFAULT 0;
CREATE INDEX IF NOT EXISTS idx_task_boards_space ON task_boards(space_id);
CREATE INDEX IF NOT EXISTS idx_task_boards_position ON task_boards(space_id, position);
CREATE INDEX IF NOT EXISTS idx_tasks_template ON tasks(template_id);
CREATE INDEX IF NOT EXISTS idx_tasks_recurring_rule ON tasks(recurring_rule_id);
CREATE INDEX IF NOT EXISTS idx_tasks_subcolumn ON tasks(subcolumn_id);
CREATE INDEX IF NOT EXISTS idx_entity_links_source ON entity_links(source_type, source_id);
CREATE INDEX IF NOT EXISTS idx_entity_links_target ON entity_links(target_type, target_id);
INSERT INTO control_types(name, is_builtin, created_at) VALUES('organizational', 1, CURRENT_TIMESTAMP) ON CONFLICT (name) DO NOTHING;
INSERT INTO control_types(name, is_builtin, created_at) VALUES('technical', 1, CURRENT_TIMESTAMP) ON CONFLICT (name) DO NOTHING;
INSERT INTO control_types(name, is_builtin, created_at) VALUES('procedural', 1, CURRENT_TIMESTAMP) ON CONFLICT (name) DO NOTHING;
UPDATE docs SET doc_type='document' WHERE doc_type IS NULL OR TRIM(doc_type)='';
UPDATE incidents SET status='draft' WHERE status IS NULL OR TRIM(status)='';
UPDATE entity_links SET source_type='doc', source_id=CAST(doc_id AS TEXT) WHERE (source_type IS NULL OR TRIM(source_type)='') AND doc_id IS NOT NULL;
UPDATE entity_links SET relation_type='related' WHERE relation_type IS NULL OR TRIM(relation_type)='';
-- +goose Down
SELECT 1;


